### ISSUE TITLE
assemble error

### ISSUE THREAD

**Issue by heekyu** [e-/Hangul.js#18]
> h.assemble(['ㅃ','ㅞ','ㄹ','ㄱ'])
'쀍'
> h.assemble(['ㅃ','ㅞ','ㄹ','ㄱ','ㅅ'])
**'\u0000' -> Error!**
> h.assemble(['ㅃ','ㅞ','ㄹ','ㄱ','ㅅ', 'ㅏ'])
'쀍사'

['ㅃ','ㅞ','ㄹ','ㄱ','ㅅ'] => '쀍ㅅ' 가 되어야 하지만 '\u0000' 이 return 됩니다.

hangul-js version : 0.2.5

**Comment by e-** [comment]
Resolved in version 0.2.6. Thank you very much!
