### ISSUE TITLE
[NOTICE] test page 디자인

### ISSUE THREAD

**Issue by sangwoojung** [e-/Hangul.js#22]
assemble과 disassemble 기능들을 test해볼 수 있는 페이지의 디자인을 입혀서 user로 하여금 조금 더 직관적으로 바꾸는 게 좋을 것 같습니다.

**Comment by sangwoojung** [comment]
관련해서 pull request 보냈습니다. 감사합니다.

**Comment by e-** [comment]
Thanks!
