### ISSUE TITLE
Hangul.indexOf()

### ISSUE THREAD

**Issue by Leftium** [e-/Hangul.js#3]
Hangul.search() 결과 값을 가지고 문자열에서 일치 되는 위치 (index) 바로 알 수 없어요. 일치된 부분만 강조 표현 하려고 하는데 일치 된 부분의 시작 위치 (또 끝 위치) 알 수 있었으면 좋겠습니다.

Hangul.indexOf() 같은 함수 만들어 봤는데, 문자열 분리전 형태 알 수 있었으면 계산이 더 쉴 것 같아요:
`["ㅎ", "ㅏ", "ㄴ", "ㄱ", "ㅡ", "ㄹ"]` 대신에 `[["ㅎ", "ㅏ", "ㄴ"], ["ㄱ", "ㅡ", "ㄹ"]]`

---

아래 저는 작성한 Hangul.indexOf() 공유합니다:
```
Hangul.indexOf = function(haystack, needle) {
  var index, match, totalLetters;
  match = 1 + Hangul.search(haystack, needle);
  totalLetters = 0;
  index = -1;
  while (totalLetters < match) {
    index++;
    totalLetters += (Hangul.disassemble(haystack[index])).length;
  }
  return index;
};
```

**Comment by e-** [comment]
Thank you for your suggestion!

**Comment by e-** [comment]
`Hangul.rangeSearch` is now available. I hope this will help. Thanks.
